version: '3'

services:
  spring-boot:
    image: fhofman/bpi-springbooti:latest
    ports:
    - "8080:8080"
  angular:
    image: fhofman/bpi-springbooti:latest
    ports:
      - "4200:4200"
    depends_on:
      - spring-boot
